---
- name: Create Prometheus directory
  file:
    path: /home/{{default_user}}/prometheus/
    state: directory  

- name: Prometheus Data Volume
  docker_volume:
    name: prometheus_data
    state: present

- name: Prometheus config file
  template:
    src: prometheus.yml.j2
    dest: /home/{{default_user}}/prometheus/prometheus.yml       

- name: Prometheus
  docker_container:
    name: "prometheus"
    image: "prom/prometheus:{{ BUILD }}"
    command: " --config.file='/etc/prometheus/prometheus.yml' --storage.tsdb.retention.time={{ RETENTION_TIME }}"
    pull: "true"
    recreate: "yes"
    env:
      TZ: "{{ TZ }}"      
    state: "started"
    restart_policy: "unless-stopped"
    published_ports:
        - "0.0.0.0:9090:9090"
    volumes:
      - /home/{{default_user}}/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus