---
- name: Create Prometheus directory
  file:
    path: /home/{{ default_user }}/{{ CONTAINER_NAME }}/
    state: directory
    mode: 0755
  tags:
  - asbrl-prometheus

- name: Prometheus Data Volume
  docker_volume:
    name: "{{ CONTAINER_NAME }}_data"
    state: "{{ VOLUME_STATE }}"
  tags:
  - asbrl-prometheus

- name: Prometheus config file
  template:
    src: prometheus.yml.j2
    dest: /home/{{ default_user }}/{{ CONTAINER_NAME }}/prometheus.yml
    mode: 0644
  tags:
  - asbrl-prometheus

- name: copy alert.rules file
  template:
    src: "alert.rules.yml.j2"
    dest: "/home/{{ default_user }}/prometheus/alert.rules.yml"
    mode: 0644
  tags:
  - asbrl-prometheus

- name: Prometheus
  docker_container:
    name: "{{ CONTAINER_NAME }}"
    image: "prom/prometheus:{{ BUILD }}"
    command: " --config.file='/etc/prometheus/prometheus.yml' --storage.tsdb.retention.time={{ RETENTION_TIME }}"
    pull: "true"
    recreate: "yes"
    env:
      TZ: "{{ TZ }}"
    cpu_period: "{{ DOCKER_CPU_PERIOD }}"
    cpu_quota: "{{ DOCKER_CPU_QUOTA }}"
    memory: "{{ DOCKER_MEMORY }}"
    state: "{{ CONTAINER_STATE }}"
    restart_policy: "unless-stopped"
    published_ports: "{{ DOCKER_PUBLISHED_PORTS | default(omit) }}"
    exposed_ports: "{{ DOCKER_EXPOSED_PORTS | default(omit) }}"
    volumes:
      - /home/{{ default_user }}/{{ CONTAINER_NAME }}/:/etc/prometheus/
      - '{{ CONTAINER_NAME }}_data:/prometheus'
    labels: "{{ DOCKER_LABELS | default(omit) }}"
  tags:
  - asbrl-prometheus